# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('comment', models.TextField(max_length=1500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
